### ISSUE TITLE
MY OWL CAROUSEL IS NOT SHOWING AT ALL...........  WHY??????????

### ISSUE THREAD

**Issue by shubhi786** [OwlCarousel2/OwlCarousel2#2654]
MY CAROUSEL IS NOT SHOWING IMAGES BUT EMPTY SCREEN . I HAVE WRITTEN THE CODE ACCURATELY BUT I THINK THERE IS A PROBLEM IN IMPORTING FILES .
THE FILES THAT I IMPORTED ARE FOLLOWING :
   CSS FILES
1 :- owl.carousel.css
2 :- owl.carousel.min.css
3 :- owl.theme.default.min.css 
4 :- bootstrap.min.css

      JS FILES
1 :- jquery.min.js 
2 :- owl.carousel.min.js
3 :- jquery-3.4.1.js
4 :- bootstrap.min.js
5 :- owl.carousel.js

PLEASE HELP ME OUT HERE . I HAVE A PROJECT TO SUBMIT .......

![Screenshot (398)](https://user-images.githubusercontent.com/49511730/64075324-8bacc700-ccd4-11e9-89c7-7781980afe9a.png)

![Screenshot (399)](https://user-images.githubusercontent.com/49511730/64075329-9bc4a680-ccd4-11e9-8a8b-6096c4627ced.png)
![Screenshot (400)](https://user-images.githubusercontent.com/49511730/64075334-a848ff00-ccd4-11e9-9e1c-39108245122c.png)

**Comment by Machosleek** [comment]
Try rearranging your Scripts by loading all Jquery first

**Comment by nathanjessen** [comment]
Verify the path to your CSS and JS is correct. I think they might be nested in your OwlCarousel folder.
Also, you don't need both the minified and unminified files. It's best to include one or the other. For example, just include the owl.carousel.js and not the owl.carousel.min.js. Only one of them is needed. The same goes for the css.

**Comment by TMRWstudio** [comment]
Have you tried inspecting the output with the browser inspector.I don't know why (and if it works without it) but the owl-carousel class in the owl.carousel.css file is set to: Display: none; If you switch this to inline-block or inline-flex or something to your liking, your images wil appear. Does not make the whole thing work.

But maybe easier to troubleshoot.

**Comment by Horlawale-ui** [comment]
Was this issues solved ...cos I have the same issues presently

**Comment by rizaljanuari** [comment]
I have the same issue, then i just do this fix. in my case i write :
`<main class ="site-main"> ... <section class="about-area">
        <div class="container">
            <div class="row text-center">
                <div class="col-12">
                    <div class="about-title">
                        <h1 class="text-uppercase title-h1">TESTIMONIALS</h1>
                        <p class="para">
                            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perferendis quos in animi numquam,
                            officiis dicta odio reiciendis incidunt facilis, libero eaque.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="container carousel py-lg-5">
            <div class="owl-carousel owl-theme">
                <div class="client row">
                    <div class="col-lg-4 col-md-12 client-img">
                        <img src="./img/testimonials/t1.jpg" alt="img1" class="img-fluid">
                    </div>
                    <div class="col-lg-8 col-md-12 about-client">
                        <h4 class="text-uppercase">John Doe</h4>
                        <p class="para">
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sint eaque nulla recusandae nihil
                            ea quibusdam omnis illo iure.
                        </p>
                    </div>
                </div>` 

then i think i must not to point the section div, just write the owl-carousel itselt in my js. here before i edit my js file : 

`$('.site-main .about-area .owl-carousel').owlCarousel({
        loop: true,
        autoplay: true,
        dots: true,
        responsive: {
            0: {
                items: 1
            },
            560: {
                items: 2
            }
        }
    })` 

and here when i fix the carousel isnt showing and greyed out when i debug in inspector: 

`$('.owl-carousel').owlCarousel({
        loop: true,
        autoplay: true,
        dots: true,
        responsive: {
            0: {
                items: 1
            },
            560: {
                items: 2
            }
        }
    })`

**Comment by koushiknagshuvo** [comment]
My "OWL CAROUSEL" is working on my local machine but it's not working on Github. How to solve it?

**Comment by ahmedesh** [comment]
i have this issue , i have solve by use 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

**Comment by Umang9427** [comment]
@ahmedesh Thank you! The issue has been solved.

**Comment by Umang9427** [comment]
I would say that,
1. Change jquery CDN to this:
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
2. If you use some other jquery sliders or code, it might interrupt OwlCarousel. In my case I had Slick Carousel, I removed it and the owl carousel started to work.

**Comment by mike99sousa** [comment]
Some months ago was working but now it stopd, doesnt show anything.  

if i inspect i see the ".owl-carousel" with "diplsy : none" . If i change in css display with inline-flex it appears, but it doesnt do the animation . If take the class (.owl-carousel) in my div, apeears in the browser to, but not in the right way. 

I already check every file and still doesnt work .  

Can someone help pls

**Comment by BlankStateOfMind** [comment]
Exact same issue however my files are indeed displayed but vertically..

**Comment by mike99sousa** [comment]
the only way its working was putting the script in the html , only that way works everything. I tried everything and wasnt working. 
I noticed to that if the script of the carousel was in the beginning of the code in my main js file, would work ,but every single line of the next code wouldnt and if the carousel script would be in any part of the code, in my main js file, it wouldnt work and the rest of the code work

**Comment by AbdulSalphan** [comment]
> Some months ago was working but now it stopd, doesnt show anything.
> 
> if i inspect i see the ".owl-carousel" with "diplsy : none" . If i change in css display with inline-flex it appears, but it doesnt do the animation . If take the class (.owl-carousel) in my div, apeears in the browser to, but not in the right way.
> 
> I already check every file and still doesnt work .
> 
> Can someone help pls

Have you resolved this issue? I'm having the same issue. I just pasted the code from the documentation to test. But, that's not working.

**Comment by chotonbhowmik** [comment]
i am also facing the same issue.but i did not find any solution yet.

**Comment by royonly** [comment]
Thank you everyone for your valuable opinions on a solution.

**Comment by sahababd4** [comment]
Hey Guys I **got the solution**.
I faces the same problem at my problem. after sometimes I noticed I missed some class which given owl-carousal given.
I inserted the class and then it was fixed
Class Name :  **owl-carousel owl-theme**
See the example=>

```
<div class="slides owl-carousel owl-theme">
    <div class="slide"></div>
    <div class="slide"></div>
    <div class="slide"></div>
    <div class="slide"></div>
</div>
```
```
<script>
  $(document).ready(function() { 
    $(".slides ").owlCarousel({
      navigation : false,
      slideSpeed : 300,
      paginationSpeed : 400,
      items : 1, 
      autoPlay:true,
      loop: true,
      nav: false,
    });
</script>
```

**Comment by silvioar** [comment]
the only solution for me was adding the js and css into the HTML.
